### ISSUE TITLE
Download episodes via playlist

### ISSUE THREAD

**Issue by OevreFlataeker** [devine-dl/devine#108]
As far as I can see, we don't have an option to download multiple episodes at once right now if the service does not allow for it. Using the iPlayer service from stabbedbybrick I usually need to run devine like this:

```
devine dl -q 720 --s-lang en --sub-format srt iP https://www.bbc.co.uk/iplayer/episode/m001ysqf/garden-rescue-series-9-1-port-sunlight
```

using the full URL to the episode.

I'd like to have a feature where I can specify `--batch downloadurls.txt` which contains the URLs of the episodes to get downloaded one-by-one.

**Comment by rlaphoenix** [comment]
This would be a problem with the service. You can download full series/seasons via iPlayer links if it was made correctly, which this service might or might not be I do not know. But let's just say it wasn't possible, then you could just edit the service's `title` CLI arg to be `nargs=-1` meaning unlimited entries, so you can pass all the links to it and then have get_titles loop through them. Or have the service accept both an URL or a txt file path that it then reads and loops through.

At the end of the day what I'm saying is this isn't something `devine dl` needs to implement at all, this is a service thing. Something that's either an issue with making the service (or using the service) wrong, or solvable by the service itself.
