### ISSUE TITLE
Download multiple resolutions in one run

### ISSUE THREAD

**Issue by Dreamer269** [devine-dl/devine#26]
**Is your feature request related to a problem? Please describe.**
Currently I have to start devine multiple times to download different resolutions like 480p, 720p and 1080p of the same video.
For services which rate limit api calls, the current solution is not optimal.

**Describe the solution you'd like**
A quality range would be an great option, where one can specify which resolutions should be downloaded. I mean once the service.get_tracks() function was called, we have all the streams with different resolutions. No need to restart devine and request them again, when we have all we need. My first guess would be to alter the code where the tracks get selected and use a for loop to select the video track by different resolutions which were served via an argument. But I think this approach is not the best. Thats why I wanted to bring this up as a request.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rlaphoenix** [comment]
Great Idea. I will add support for this soon.
