### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by dAtBigFish** [devine-dl/devine#34]
**Is your feature request related to a problem? Please describe.**
Ability to set a scheduled date/time for download to happen. IE. automate the download process if the user is unable to manually trigger the command at desired time.

**Describe the solution you'd like**
Scheduler should be able to set and remember given input and execute the command on desired date/time

**Comment by rlaphoenix** [comment]
You're basically asking for what is already requested in #6. However, what you ask for could be done using Task Scheduler on Windows or crontab on Linux.
