### ISSUE TITLE
Pycaption destroys subtitle formatting

### ISSUE THREAD

**Issue by dAtBigFish** [devine-dl/devine#39]
**Describe the bug**
When subtitle goes through pycaption processing it destroys all of the subtitle formatting, ie. positioning, italics, etc...
This could be fixed by using another subtitle processor which does have better processing.
**To Reproduce**

When we compare a raw subtitle (.vtt) before converting to .srt via pycaption it keeps all of the positioning and styling data, which should always be the case since subtitles after going through pycaption looks ugly.

**Expected behavior**
Pycaption should either be replaced or modified to keep the formatting untouched.

**Screenshots**
Basic example can be seen here: 
![FTmBltDbUA](https://user-images.githubusercontent.com/17677208/223128024-0c96c72f-9005-4c53-a6d0-8d0d450e4c5c.png)

Taken from HBO Max as they do have really nice subtitle formatting but after it's conversion all is gone.
See italic tags and positioning ({\an8}) tags.

**Comment by rlaphoenix** [comment]
I know of https://github.com/Paco8/ttml2ssa and a new project https://github.com/vevv/subby, but I'm open to suggestions. I specifically use pycaption as it's incredibly versatile, and basically required for some of my subtitle processing code. E.g., converting fragmented MP4 subtitles like fVTT and fTTML.

I think the best solution would be to keep support for the format in pycaption.

**Comment by dAtBigFish** [comment]
This might be true on pycaption that is versatile, however killing the formatting is not really good idea aswell. If it's possible to leave pycaption for where you really need it, fVTT or fTTML and let the ttml2ssa or subby do the work on the rest of the stuff.
