### ISSUE TITLE
Ability to monitor a title for new episodes and automatically download them

### ISSUE THREAD

**Issue by rlaphoenix** [devine-dl/devine#6]
**Is your feature request related to a problem? Please describe.**
This could be really nice when you're expecting new episodes to come out and want it downloaded as soon as possible.

**Describe the solution you'd like**
A clone or shell wrapper over `dl` command called `monitor`, that will re-run the `dl` command until it does not error. We would also need to clone or passthrough arguments to the dl command.

**Describe alternatives you've considered**
I cant think of any other good ways to do this. Suggestions are welcome.

**Additional context**
We would need to take care with rate limits. How would we stop users from accidentally having it running for an outrageous amount of time pre-maturely?

**Comment by Dreamer269** [comment]
Some services like Crunchyroll offer an rss feed. You could implement a rss parser into devine. One then can update the specific service code to extend the rss parser for each service. This way devine could check wether a new episode is available or not. No need to fight with rate limits. What do you think about this idea?

**Comment by rlaphoenix** [comment]
> Some services like Crunchyroll offer an rss feed. You could implement a rss parser into devine. One then can update the specific service code to extend the rss parser for each service. This way devine could check wether a new episode is available or not. No need to fight with rate limits. What do you think about this idea?

Well in practice that would be best, but almost no other service does this and I'd want the feature to work across all implemented services.

**Comment by Dreamer269** [comment]
Hm yes, I see the problem. But there have to be some sort of service specific endpoints to return new episodes (doesn't have to be rss). Personally I dont think that running devine x times until the episode downloads is a good solution xD. But seems like this is the only solution so far ...

**Comment by rsgrt** [comment]
Some series have regular set time when a new episode is uploaded. Maybe something where a user can set the time/date to check on a config file then devine will check at random set intervals after the set date/time?

**Comment by rlaphoenix** [comment]
Closing this as I feel like this would be functionality bloat. One could easily implement this themselves outside of devine by calling devine through CLI in scripts like Subprocess in Python.
