### ISSUE TITLE
download speed drop in v3!

### ISSUE THREAD

**Issue by Lacanbonda** [devine-dl/devine#84]
**Describe the bug**
v3 is slower in download speed, whereas version v2.2.0 is faster.

**Screenshots**
v3.0.0
![Screenshot_5](https://github.com/devine-dl/devine/assets/105432999/f01f761d-c0c7-47a6-8de3-9277f4b6d31f)

v2.2.0
![Screenshot_6](https://github.com/devine-dl/devine/assets/105432999/1f41e1ae-3edf-49b0-a38f-d3eb453a72c5)

**Additional context**
v3.1.0 also slow

**Comment by rlaphoenix** [comment]
Hi, this is a known problem specifically with DASH in https://github.com/devine-dl/devine/issues/75
