### ISSUE TITLE
Feature: Save previously downloaded titles

### ISSUE THREAD

**Issue by Sp5rky** [devine-dl/devine#91]
**Is your feature request related to a problem? Please describe.**
```
--new
This will only download new episodes that have not been downloaded previously when saved with --keep
```
```
--keep
This will save the episode to db based on the config similar to key_vaults
```
 
**Describe the solution you'd like**
So if we do ``devine dl -w S01E01-S01E50 --keep <SERVICE> <TITLE>`` it'll save all these records
and then when we do ``devine dl -w S01E01-S01E100 --new <SERVICE> <TITLE>`` we've previously downloaded episodes 1-50 so it'll start at 51-100

Could even make --new --keep a default option in devine.yaml
```features:
  keep: yes
  new: yes
```

**Describe alternatives you've considered**
Attempted to achieve this within the service, but a function within the dl.py will be better and easier to handle.

**Comment by rlaphoenix** [comment]
I don't think I'll be doing this. It's just not a feature I want in devine.
